# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-26 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceprint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiomodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='audiomodel',
            name='aid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
